apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3-pv
spec:
  capacity:
    storage: 1200Gi # ignored, required
  accessModes:
    - ReadWriteMany # supported options: ReadWriteMany / ReadOnlyMany
  mountOptions:
    - allow-delete
    - region $AWS_REGION
    # - prefix some-s3-prefix/
  csi:
    driver: s3.csi.aws.com # required
    volumeHandle: s3-csi-driver-volume
    volumeAttributes:
      bucketName: $S3_BUCKET
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s3-claim
spec:
  accessModes:
    - ReadWriteMany # supported options: ReadWriteMany / ReadOnlyMany
  storageClassName: "" # required for static provisioning
  resources:
    requests:
      storage: 1200Gi # ignored, required
  volumeName: s3-pv
---
apiVersion: v1
kind: Pod
metadata:
  name: s3-app
spec:
  nodeSelector:
    karpenter.sh/nodepool: default
  containers:
  - name: download
    # image: public.ecr.aws/u3r1l1j7/eks-genai:neuronrayvllm-100G
    image: shaowenchen/huggingface-cli
    command:
    - huggingface-cli
    - download
    - "enghwa/neuron-mistral7bv0.2"
    - "--local-dir"
    - "/work-dir/Mistral-7B-Instruct-v0.2"
  volumeMounts:
      - name: persistent-storage
        mountPath: /work-dir
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: s3-claim