apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vllm-mistral-servicemonitor
  namespace: kube-system
  labels:
    release: kube-prometheus-stack   # Make sure this matches the Prometheus release label selector
    app: vllm-mistral-inf2-server
spec:
  selector:
    matchLabels:
      app: vllm-mistral-inf2-server    # Label on your Kubernetes service
  namespaceSelector:
    matchNames:
      - default          # Namespace where your service is running
  endpoints:
  - port: http    # The port name exposed by your service for metrics
    path: /metrics        # Metrics endpoint path
    interval: 15s         # Scrape interval
    scheme: http
    targetPort: 8000
